### ISSUE TITLE
loop_forever() being deprecated in adafruit_minimqtt

### ISSUE THREAD

**Issue by 2bndy5** [adafruit/Adafruit_CircuitPython_GC_IOT_Core#13]
the [loop_forever() method](https://github.com/adafruit/Adafruit_CircuitPython_GC_IOT_Core/blob/95195b7f8ff8cce84452403d80682e82dda8f7e4/adafruit_gc_iot_core.py#L217-L222) is being deprecated on next planned release of adafruit_minimqtt library. Opening this issue as a reminder in accordance with [this PR comment](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/pull/46#discussion_r458878274)

**Comment by brentru** [comment]
Released in https://github.com/adafruit/Adafruit_CircuitPython_GC_IOT_Core/releases/tag/3.0.0
